cc_test(
    name = "add_two_numbers_test",
    srcs = ["add_two_numbers_test.cpp"],
    deps = [
        "//01-Add-Two-Numbers/src:add_two_numbers",
        "@com_google_googletest//:gtest_main",
    ],
)
