cc_test(
    name = "backwards_substitution_test",
    srcs = ["backwards_substitution_test.cpp"],
    deps = [
        "//Backwards-Substitution/src:backwards_substitution",
        "@com_google_googletest//:gtest_main",
    ],
)
